replicaCount: 1
resources:
  requests:
    cpu: 50m
    memory: 120Mi
image:
  tag: 'a7f6b1'
httpRoute:
  enabled: false
  hostnames: []
  parentRefs: []
  rules: []
ingress:
  enabled: false
  hosts: []
  tls: []
service:
  type: ClusterIP
  port: 80
