apiVersion: v1
kind: Secret
metadata:
  name: fast-api-secret
type: kubernetes.io/dockercfg
stringData:
  .dockercfg: |
    {
      "docker.io": {
        "username": "scoronadovasco",
        "password": "",
        "email": "tu_email@example.com",
        "auth": ""
      }
    }